/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.mortalKombat.views;

import autonoma.mortalKombat.models.Simulador;

/**
 *
 * @author juand
 */
public class PantallaNiveles extends javax.swing.JFrame {
    private Simulador simulador;

    public PantallaNiveles(Simulador simulador) {
        this.simulador = simulador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            private java.awt.Image fondo = new javax.swing.ImageIcon(getClass().getResource("/images/fondoNiveles.png")).getImage();
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        homeButton = new javax.swing.JLabel();
        nivel1Button = new javax.swing.JLabel();
        nivel2Button = new javax.swing.JLabel();
        nivel3Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoHome.png"))); // NOI18N
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        nivel1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel1.png"))); // NOI18N
        nivel1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel1ButtonMouseClicked(evt);
            }
        });

        nivel2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel2.png"))); // NOI18N
        nivel2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel2ButtonMouseClicked(evt);
            }
        });

        nivel3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel3.png"))); // NOI18N
        nivel3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel3ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(nivel1Button)
                        .addGap(50, 50, 50)
                        .addComponent(nivel2Button)
                        .addGap(53, 53, 53)
                        .addComponent(nivel3Button)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(homeButton)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivel2Button)
                    .addComponent(nivel1Button)
                    .addComponent(nivel3Button))
                .addGap(0, 114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        PantallaDeInicio inicio = new PantallaDeInicio(simulador);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void nivel1ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        abrirBatalla(1);
    }

    private void nivel2ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        abrirBatalla(2);
    }

    private void nivel3ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        abrirBatalla(3);
    }                                          

    private void abrirBatalla(int nivel) {
        try {
            simulador.seleccionarNivel(nivel);
            CampoBatalla batalla = new CampoBatalla(nivel, simulador);
            batalla.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            // Si usas NivelBloqueadoException, puedes mostrar un mensaje aquí
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Nivel bloqueado", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nivel1Button;
    private javax.swing.JLabel nivel2Button;
    private javax.swing.JLabel nivel3Button;
    // End of variables declaration//GEN-END:variables
}
