/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.mortalKombat.views;

import autonoma.mortalKombat.models.Simulador;

/**
 *
 * @author juand
 */
public class PantallaNiveles extends javax.swing.JFrame {
    private Simulador simulador;

    public PantallaNiveles(Simulador simulador) {
        this.simulador = simulador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivel1Button = new javax.swing.JLabel();
        nivel2Button = new javax.swing.JLabel();
        nivel3Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        nivel1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel1.png"))); // NOI18N
        nivel1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel1ButtonMouseClicked(evt);
            }
        });

        nivel2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel2.png"))); // NOI18N
        nivel2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel2ButtonMouseClicked(evt);
            }
        });

        nivel3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nivel3.png"))); // NOI18N
        nivel3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nivel3ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(nivel1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(nivel2Button)
                .addGap(44, 44, 44)
                .addComponent(nivel3Button)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivel3Button)
                    .addComponent(nivel2Button)
                    .addComponent(nivel1Button))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivel1ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        simulador.seleccionarNivel(1);
    }

    private void nivel2ButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        simulador.seleccionarNivel(2);
    }

    private void nivel3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nivel3ButtonMouseClicked
        simulador.seleccionarNivel(3);
    }//GEN-LAST:event_nivel3ButtonMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nivel1Button;
    private javax.swing.JLabel nivel2Button;
    private javax.swing.JLabel nivel3Button;
    // End of variables declaration//GEN-END:variables
}
