/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.mortalKombat.views;

import autonoma.mortalKombat.models.Simulador;
import autonoma.mortalKombat.models.Jugador;
import autonoma.mortalKombat.models.Tienda;
import autonoma.mortalKombat.exceptions.PuntosInsuficientesException;

/**
 *
 * @author juand
 */
public class PantallaTienda extends javax.swing.JFrame {
    private Simulador simulador;

    /**
     * Creates new form PantallaTienda
     */
    public PantallaTienda(Simulador simulador) {
        this.simulador = simulador;
        initComponents();
        actualizarPuntos();

        // Acción para el botón confirmar
        confirmarCambiosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaDeInicio inicio = new PantallaDeInicio(simulador);
                inicio.setVisible(true);
                dispose(); // Cierra la tienda
            }
        });
    }

    private void actualizarPuntos() {
        puntosActualesLabel.setText(String.valueOf(simulador.getJugador().getPuntos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        puntosActualesLabel = new javax.swing.JLabel();
        mejorarVidaButton = new javax.swing.JButton();
        aumentarDañoButton = new javax.swing.JButton();
        confirmarCambiosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("Tienda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("Puntos Actuales:");

        puntosActualesLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        puntosActualesLabel.setForeground(new java.awt.Color(153, 153, 0));
        puntosActualesLabel.setText("0");

        mejorarVidaButton.setBackground(new java.awt.Color(153, 153, 0));
        mejorarVidaButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mejorarVidaButton.setForeground(new java.awt.Color(0, 0, 0));
        mejorarVidaButton.setText("Mejorar vida : $250");
        mejorarVidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejorarVidaButtonActionPerformed(evt);
            }
        });

        aumentarDañoButton.setBackground(new java.awt.Color(153, 153, 0));
        aumentarDañoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aumentarDañoButton.setForeground(new java.awt.Color(0, 0, 0));
        aumentarDañoButton.setText(" Aumentar daño : $250");
        aumentarDañoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarDañoButtonActionPerformed(evt);
            }
        });

        confirmarCambiosButton.setBackground(new java.awt.Color(153, 153, 0));
        confirmarCambiosButton.setForeground(new java.awt.Color(0, 0, 0));
        confirmarCambiosButton.setText("confirmar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(puntosActualesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aumentarDañoButton)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(mejorarVidaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(confirmarCambiosButton)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(puntosActualesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mejorarVidaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aumentarDañoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(confirmarCambiosButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mejorarVidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejorarVidaButtonActionPerformed
        try {
            simulador.getTienda().comprarMejoraVida(simulador.getJugador());
        } catch (PuntosInsuficientesException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Puntos insuficientes", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        actualizarPuntos();
    }//GEN-LAST:event_mejorarVidaButtonActionPerformed

    private void aumentarDañoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarDañoButtonActionPerformed
        simulador.getTienda().comprarMejoraDaño(simulador.getJugador());
        actualizarPuntos();
    }//GEN-LAST:event_aumentarDañoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarDañoButton;
    private javax.swing.JButton confirmarCambiosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mejorarVidaButton;
    private javax.swing.JLabel puntosActualesLabel;
    // End of variables declaration//GEN-END:variables
}
